name: setup-helmfile
description: 'Setup helmfile Action'
author: "mamezou-tech"
branding:
  icon: 'arrow-right-circle'
  color: 'purple'
inputs:
  kubectl-version:
    description: "kubectl (AWS edition) version"
    default: "1.19.6"
    required: false
  kubectl-release-date:
    description: "kubectl (AWS edition) release date"
    default: "2021-01-05"
    required: false
  vals-version:
    description: "vals version"
    default: "0.14.0"
    required: false
  sops-version:
    description: "sops version"
    default: "v3.7.1"
    required: false
  helm-version:
    description: "Helm version"
    default: "v3.5.3"
    required: false
  helmfile-version:
    description: "helmfile version"
    default: "v0.138.7"
    required: false
  install-kubectl:
    description: "Install kubectl"
    default: "yes"
    required: false
  install-vals:
    description: "install vals"
    default: "yes"
    required: false
  install-sops:
    description: "install sops"
    default: "yes"
    required: false
  install-helm:
    description: "Install helm"
    default: "yes"
    required: false
  install-helm-plugins:
    description: "Install Helm plugins"
    default: "yes"
    required: false
  additional-helm-plugins:
    description: |
      A comma separated list of additional helm plugins to install. Should be a valid argument after `helm plugin install`.
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
