name: setup-helmfile
description: 'Setup helmfile Action'
author: "mamezou-tech"
branding:
  icon: 'arrow-right-circle'
  color: 'purple'
inputs:
  kubectl-version:
    description: "kubectl (AWS edition) version"
    default: "1.14.6"
    required: false
  kubectl-release-date:
    description: "kubectl (AWS edition) release date"
    default: "2019-08-22"
    required: false
  helm-version:
    description: "Helm version"
    default: "v3.0.3"
    required: false
  helmfile-version:
    description: "helmfile version"
    default: "v0.98.3"
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
