name: setup-helmfile
description: 'Setup helmfile Action'
author: "mamezou-tech"
branding:
  icon: 'arrow-right-circle'
  color: 'purple'
inputs:
  kubectl-version:
    description: "kubectl (AWS edition) version"
    default: "1.32.0"
    required: false
  kubectl-release-date:
    description: "kubectl (AWS edition) release date"
    default: "2025-01-10"
    required: false
  helm-version:
    description: "Helm version"
    default: "v3.17.0"
    required: false
  helmfile-version:
    description: "helmfile version"
    default: "v0.170.1"
    required: false
  install-kubectl:
    description: "Install kubectl"
    default: "yes"
    required: false
  install-helm:
    description: "Install helm"
    default: "yes"
    required: false
  install-helm-plugins:
    description: "Install Helm plugins"
    default: "yes"
    required: false
  helm-diff-plugin-version:
    description: "Version of the helm diff plugin to install"
    default: "v3.9.14"
    required: false
  helm-s3-plugin-version:
    description: "Version of the helm s3 plugin to install"
    default: "v0.16.2"
    required: false
  additional-helm-plugins:
    description: |
      A comma separated list of additional helm plugins to install. Should be a valid argument after `helm plugin install`.
    required: false
runs:
  using: "node20"
  main: "dist/index.js"
