name: setup-helmfile
description: 'Setup helmfile Action'
author: "mamezou-tech"
branding:
  icon: 'arrow-right-circle'
  color: 'purple'
inputs:
  kubectl-version:
    description: "kubectl (AWS edition) version"
    default: "1.16.13"
    required: false
  kubectl-release-date:
    description: "kubectl (AWS edition) release date"
    default: "2020-08-04"
    required: false
  helm-version:
    description: "Helm version"
    default: "v3.3.1"
    required: false
  helmfile-version:
    description: "helmfile version"
    default: "v0.126.2"
    required: false
  install-kubectl:
    description: "Install kubectl"
    default: "yes"
    required: false
  install-helm:
    description: "Install helm"
    default: "yes"
    required: false
  install-helm-plugins:
    description: "Install Helm plugins"
    default: "yes"
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
